apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s4u-gitops-agent
  namespace: k8s4u-gitops-agent
  labels:
    app.kubernetes.io/name: k8s4u-gitops-agent
    app.kubernetes.io/managed-by: k8s4u-gitops-agent
    kubernetes.io/metadata.name: k8s4u-gitops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s4u-gitops-agent
  template:
    metadata:
      labels:
        app: k8s4u-gitops-agent
    spec:
      serviceAccountName: k8s4u-gitops-agent
      securityContext:
        fsGroup: 2000
      containers:
      - name: k8s4u-gitops-agent
        image: k8s4u/gitops-agent:dev-v63
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: GITREPO
          value: https://github.com/k8s4u/gitops-agent.git
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: gitops-tmpfs
            mountPath: /gitops
          - name: git-auth
            mountPath: /git-auth
      volumes:
        - name: gitops-tmpfs
          emptyDir: {}
        - name: git-auth
          secret:
            secretName: git-pat-token
