apiVersion: v1
kind: Service
metadata:
  name: k8s4u-gitops-agent
  namespace: k8s4u-gitops-agent
  labels:
    app.kubernetes.io/name: k8s4u-gitops-agent
    app.kubernetes.io/managed-by: k8s4u-gitops-agent
    kubernetes.io/metadata.name: k8s4u-gitops-agent
spec:
  type: NodePort
  selector:
    app: k8s4u-gitops-agent
  ports:
    - nodePort: 30778
      protocol: TCP
      port: 8080
