apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s4u-gitops-agent
  namespace: k8s4u-gitops-agent
  labels:
    app.kubernetes.io/name: k8s4u-gitops-agent
    app.kubernetes.io/managed-by: k8s4u-gitops-agent
    kubernetes.io/metadata.name: k8s4u-gitops-agent
